### ISSUE TITLE
Add pre-commit.ci

### ISSUE THREAD

**Issue by ianhi** [tlambert03/pymmcore-plus#27]
See https://pre-commit.ci/ it's pretty nice as it will auto push fixes to PRs that have linting issues. Not everyone may install the pre-commit hooks, and this also allows for fixing changes made directly via github ui.

example commit: https://github.com/ianhi/mpl-interactions/pull/203/commits/1589939aac96b45ce3f41e971044ff35ee6b2e52

**Comment by tlambert03** [comment]
yep, got it on all my other repos :) love it.

**Comment by tlambert03** [comment]
added
