### ISSUE TITLE
Always call `unloadAllDevices` on exit

### ISSUE THREAD

**Issue by ianhi** [tlambert03/pymmcore-plus#42]
If you kill a python process that has a connection to a microscope without calling `mmcore.unloadAllDevices` then you can end up trapped and potentially need to restart both the computer and the microscope. I think this could often be prevented if we used `atexit` to call `mmcore.unloadAllDevices()` which frees up the connections.

**Comment by tlambert03** [comment]
sounds good.  this would be on the remote process right?

**Comment by ianhi** [comment]
In the case of using the pyro server than yes in the remote process, but ideally this should also be available to someone use `CMMCorePlus`
