### ISSUE TITLE
Integration with Napari?

### ISSUE THREAD

**Issue by ianhi** [tlambert03/pymmcore-plus#7]
Is there any existing integration with Napari (or matplotlib etc) for viewing the images while setting up an acquisition. If there is something nascent I'd be very happy to help with it.

**Comment by tlambert03** [comment]
indeed!  https://github.com/tlambert03/napari-micromanager

and "nascent" is a good word for it.  it's more of an experiment at that @fdrgsp and I are playing with at this point, with more than enough missing functionality and bugs to go around :)  and we've yet to actually use it on a real microscope... 

but there's a basic GUI for snap/live, as well as setting up and monitoring a standard 5D experiment:

<img width="1426" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/124185835-7b5d0300-da89-11eb-86c0-cbf7d2111232.png">

there's no documentation anywhere, so using it may require a little "inside" knowledge ... but you're more than welcome to dig in, and contribute if you're so inclined.
