### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by ianhi** [tlambert03/pymmcore-plus#95]
This test

https://github.com/tlambert03/pymmcore-plus/blob/0755f44ff235dbb5a9e86dcddeca35c29e4de6fb/pymmcore_plus/_tests/test_core.py#L405-L443

 has been pretty flaky. Failing with:
```
         th = Thread(target=trigger_cb)
>       with qtbot.waitSignal(core.events.XYStagePositionChanged):
E       AttributeError: 'NoneType' object has no attribute 'start'

pymmcore_plus/_tests/test_core.py:428: AttributeError
```

https://github.com/tlambert03/pymmcore-plus/runs/5360322257?check_suite_focus=true

which is awful confusing because there doesn't seem to be a reasonable mechanism for `th` to be `None` there.

**Comment by tlambert03** [comment]
yeah, I saw that a few times locally as well.  Super strange.  I even went as far as using `if type(th) is not type(None)` ... and it _still_ happened.  really quite something :) as soon as you add a breakpoint, `th.start()` works.

I will note that it only ever happens with psygnal, not qcorecallbacks ... but there too, I can't conceive of why.
